# This is a basic workflow that is manually triggered

name: Github action for running docker pod5 conversion

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


  
    # User inputs for the workflow
    inputs:
      INPUT_PATH:
        description: 'Input path for the .fast5 files'
        # Default value if no value is explicitly provided
        default: '/pool/sun.ghrunner/gh.test/fast5'
        # Default value if no value is explicitly provided
        required: true
        # The data type of the input
        type: string

      OUTPUT_PATH:
        description: 'Output path for the .pod5 files'
        # Default value if no value is explicitly provided
        default: '/pool/sun.ghrunner/gh.test/pod5'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      JOB_NAME:
        description: 'Give your job a name'
        # Default value if no value is explicitly provided
        default: 'pod5_conversion'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      THREAD_NUM:
        description: 'Thread number for conversion processing'
        # Default value if no value is explicitly provided
        default: "8"
         # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

      RUN_LOCATION:
        description: 'Location of the runtime environment'
        # Default value if no value is explicitly provided
        default: 'pipeline'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  pod5_conversion:
  
    name: Pod5 File Conversion
    runs-on: 
      group: ${{ github.event.inputs.RUN_LOCATION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull slreg.yutg.net/p/cuhkhaosun/code-docker-pod5:latest

    - name: Remove any old running container
      run: |
          docker rm -f "${{ github.event.inputs.JOB_NAME }}_container"

    - name: Run container with environment variables
      run: |
          docker run --name "${{ github.event.inputs.JOB_NAME }}_container" \
            -v ${{ github.event.inputs.INPUT_PATH }}:/mnt/in \
            -v ${{ github.event.inputs.OUTPUT_PATH }}:/mnt/out \
            -e JOB_NAME=${{ github.event.inputs.JOB_NAME }} \
            -e THREAD_NUM=${{ github.event.inputs.THREAD_NUM }} \
            slreg.yutg.net/p/cuhkhaosun/code-docker-pod5:latest

    - name: Stop and remove container
      run: |
          docker stop "${{ github.event.inputs.JOB_NAME }}_container"
          docker rm "${{ github.event.inputs.JOB_NAME }}_container"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch-suffix: short-commit-hash

        commit-message: |
          Add result for ${{ github.event.inputs.JOB_NAME }}
          This is auto uploaded commit

        branch: result-${{ github.event.inputs.JOB_NAME }}
        delete-branch: true

        title: '[Demo] Add report for Pod5 conversion ${{ github.event.inputs.JOB_NAME }}'
        body: |
            Update report
            - Auto-generated by github action `Pipeline for fast5 to pod5 conversion`
